### ISSUE TITLE
create-&-style-Header-&-Jumbo

### ISSUE THREAD

**Issue by WojciechPotoniec** [WojciechPotoniec/Vue-BoolBnB#1]
Buongiorno le chiediamo di strutturare e stilizzare i seguenti componenti all'interno del progetto Bool-BnB.

Avete a disposizione il figma strutturato in precedenza insieme al nostro grafico con tutti i relativi dettagli.

Grazie e buon lavoro :)

**Comment by itsjackie00** [comment]
created what you asked me to do.
